// <auto-generated />
using System;
using AppSistemaDeCelulares.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppSistemaDeCelulares.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251209161046_NewDBCelLPhones")]
    partial class NewDBCelLPhones
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppSistemaDeCelulares.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("DateRegister")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("AppSistemaDeCelulares.Models.Delivery", b =>
                {
                    b.Property<int>("DeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeliveryId"));

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("PhoneDeviceId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("DeliveryId");

                    b.HasIndex("PhoneDeviceId")
                        .IsUnique();

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("AppSistemaDeCelulares.Models.Diagnostic", b =>
                {
                    b.Property<int>("DiagnosisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiagnosisId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<decimal>("EstimatedCost")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("PhoneDeviceId")
                        .HasColumnType("int");

                    b.Property<int>("TechnicianId")
                        .HasColumnType("int");

                    b.HasKey("DiagnosisId");

                    b.HasIndex("PhoneDeviceId");

                    b.HasIndex("TechnicianId");

                    b.ToTable("Diagnostics");
                });

            modelBuilder.Entity("AppSistemaDeCelulares.Models.Part", b =>
                {
                    b.Property<int>("PartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("PartId");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("AppSistemaDeCelulares.Models.PhoneDevice", b =>
                {
                    b.Property<int>("PhoneDeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhoneDeviceId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("IMEI")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("PhoneDeviceId");

                    b.HasIndex("CustomerId");

                    b.ToTable("PhoneDevices");
                });

            modelBuilder.Entity("AppSistemaDeCelulares.Models.Repair", b =>
                {
                    b.Property<int>("RepairId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RepairId"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LaborCost")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("PhoneDeviceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("TechnicianId")
                        .HasColumnType("int");

                    b.HasKey("RepairId");

                    b.HasIndex("PhoneDeviceId");

                    b.HasIndex("TechnicianId");

                    b.ToTable("Repairs");
                });

            modelBuilder.Entity("AppSistemaDeCelulares.Models.RepairDetail", b =>
                {
                    b.Property<int>("RepairDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RepairDetailId"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("DiagnosticDiagnosisId")
                        .HasColumnType("int");

                    b.Property<int?>("PartId")
                        .HasColumnType("int");

                    b.Property<int>("RepairId")
                        .HasColumnType("int");

                    b.HasKey("RepairDetailId");

                    b.HasIndex("DiagnosticDiagnosisId");

                    b.HasIndex("PartId");

                    b.HasIndex("RepairId");

                    b.ToTable("RepairDetails");
                });

            modelBuilder.Entity("AppSistemaDeCelulares.Models.Technician", b =>
                {
                    b.Property<int>("TechnicianId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TechnicianId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(85)
                        .HasColumnType("nvarchar(85)");

                    b.HasKey("TechnicianId");

                    b.ToTable("Technicians");
                });

            modelBuilder.Entity("AppSistemaDeCelulares.Models.Delivery", b =>
                {
                    b.HasOne("AppSistemaDeCelulares.Models.PhoneDevice", "PhoneDevice")
                        .WithOne("Delivery")
                        .HasForeignKey("AppSistemaDeCelulares.Models.Delivery", "PhoneDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhoneDevice");
                });

            modelBuilder.Entity("AppSistemaDeCelulares.Models.Diagnostic", b =>
                {
                    b.HasOne("AppSistemaDeCelulares.Models.PhoneDevice", "PhoneDevice")
                        .WithMany("Diagnostics")
                        .HasForeignKey("PhoneDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppSistemaDeCelulares.Models.Technician", "Technician")
                        .WithMany("Diagnoses")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhoneDevice");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("AppSistemaDeCelulares.Models.PhoneDevice", b =>
                {
                    b.HasOne("AppSistemaDeCelulares.Models.Customer", "Customer")
                        .WithMany("PhoneDevices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("AppSistemaDeCelulares.Models.Repair", b =>
                {
                    b.HasOne("AppSistemaDeCelulares.Models.PhoneDevice", "PhoneDevice")
                        .WithMany("Repairs")
                        .HasForeignKey("PhoneDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppSistemaDeCelulares.Models.Technician", "Technician")
                        .WithMany("Repairs")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhoneDevice");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("AppSistemaDeCelulares.Models.RepairDetail", b =>
                {
                    b.HasOne("AppSistemaDeCelulares.Models.Diagnostic", null)
                        .WithMany("ListRepairDetails")
                        .HasForeignKey("DiagnosticDiagnosisId");

                    b.HasOne("AppSistemaDeCelulares.Models.Part", "Part")
                        .WithMany("ListRepairDetails")
                        .HasForeignKey("PartId");

                    b.HasOne("AppSistemaDeCelulares.Models.Repair", "Repair")
                        .WithMany("ListRepairDetails")
                        .HasForeignKey("RepairId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("Repair");
                });

            modelBuilder.Entity("AppSistemaDeCelulares.Models.Customer", b =>
                {
                    b.Navigation("PhoneDevices");
                });

            modelBuilder.Entity("AppSistemaDeCelulares.Models.Diagnostic", b =>
                {
                    b.Navigation("ListRepairDetails");
                });

            modelBuilder.Entity("AppSistemaDeCelulares.Models.Part", b =>
                {
                    b.Navigation("ListRepairDetails");
                });

            modelBuilder.Entity("AppSistemaDeCelulares.Models.PhoneDevice", b =>
                {
                    b.Navigation("Delivery");

                    b.Navigation("Diagnostics");

                    b.Navigation("Repairs");
                });

            modelBuilder.Entity("AppSistemaDeCelulares.Models.Repair", b =>
                {
                    b.Navigation("ListRepairDetails");
                });

            modelBuilder.Entity("AppSistemaDeCelulares.Models.Technician", b =>
                {
                    b.Navigation("Diagnoses");

                    b.Navigation("Repairs");
                });
#pragma warning restore 612, 618
        }
    }
}
